### ISSUE TITLE
Store data on EEPROM when power fail 

### ISSUE THREAD

**Issue by fani625** [damogranlabs/dl-menu#2]
I am using  internal band gap voltage measurement in one of my sketch for home automation which only write the data on EEPROM when power fail. If we can add in the library it will increase the life of  EEPROM .  Or if I want to use  external  EEPROM  than what I should add.

Sketch for band gap measurement is only for  arduino UNO, nano and mini:

unsigned int ADCValue;
double Voltage;
double Vcc;

long readVcc() {
  long result;
  // Read 1.1V reference against AVcc
  ADMUX = _BV(REFS0) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
  delay(2); // Wait for Vref to settle
  ADCSRA |= _BV(ADSC); // Convert
  while (bit_is_set(ADCSRA,ADSC));
  result = ADCL;
  result |= ADCH<<8;
  result = 1125300L / result; // Back-calculate AVcc in mV
  return result;
}

void setup() {
  Serial.begin(9600);
  Vcc = readVcc()/1000.0;
ADCValue = analogRead(0);
Voltage = (ADCValue / 1024.0) * Vcc;

pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  Serial.println( readVcc());

 while(readVcc() <4900){
 digitalWrite(LED_BUILTIN, HIGH);}
delay(300);
}

**Comment by FranzBangar** [comment]
Does this sketch need any additional hardware other than plain arduino board?
I was thinking about storing changed settings to EEPROM right away and came to a conclusion that 100 000 changes is a lot - especially when the user will have to do it by hand with the 4 available buttons.

**Comment by fani625** [comment]
No it did not require any additional hardware. You can try to upload above sketch in Arduino UNO and power it through VCC it will work and once voltage drop below 4.9 V (4900) than digitalWrite(LED_BUILTIN, HIGH); .
I am already using this sketch and can write on EEPROM successfully.  3 millisecond is enough to write an address. if we have dozen of values to write than simply add bulk capacitor or use power adopter with transformer which will give more time to write the addresses.

Definitely 100 000  is much more than enough and can easily goes up to 10 years.

I am happy with current version of library and specially after last update more easy.

I am try to add pushbutton which detect long press to enter in configuration menu if you can help me .

Thanks,

**Comment by FranzBangar** [comment]
A menu item saves changes only after it's been hidden and even then only the bytes that have changed (text characters). Although your proposal makes sense, it will cause trouble when analog ports will be used for anything else than voltage monitoring.
About the long press for entry, you can use the Button objects as you wish and only do menu.check() after a long press has been detected. This is beyond the scope of the menu library.

**Comment by fani625** [comment]
This voltage monitoring is not through analog pin . Its internal band gap voltage . 
Ref 
"https://jeelabs.org/2012/05/04/measuring-vcc-via-the-bandgap/"

Thanks for last updates now it completely cover almost every type of entries.  Last thing to know how select / calculate  "DLM_ADDR_TEST"     //the eeprom address of the index

**Comment by FranzBangar** [comment]
Thanks for that link, it clears up many things. I'll throw some numbers in calculator to see how much data can be saved on power off on Arduino and stand-alone circuits (Atmega/Attiny).
For selecting addresses, you need to know how much space your data takes up:
4 bytes for integer, 4 for float, 1 for choice and 1 byte per character of text; so in the example I selected addresses:
DLM_ADDR_TESTINT 0
DLM_ADDR_TESTFLOAT 4
DLM_ADDR_TESTCHOICE 8
DLM_ADDR_TESTTEXT 9
Since I defined text 8 characters long, the next entry would be at address 17. As defined, these addresses place all entries in EEPROM without any other data/empty spaces. You could select any address in Arduino EEPROM (1024 bytes) as long as it doesn't overlap with other stuff that will overwrite or doesn't go over the last byte.
