### ISSUE TITLE
How can compare text data 

### ISSUE THREAD

**Issue by fani625** [damogranlabs/dl-menu#4]
Dear,
In your last update you add "miTestText" its working fine when we print it.But how we can compare it in if statement.

In below example code "Y" or "N" is not printing. I am trying to use this text as a comparison between values.

    lcd.setCursor(0, 1);
    lcd.print("Text:");
    lcd.print(miTestText->getValue());

    if (miTestText->getValue() == 123456) {
      lcd.setCursor(13, 1);
      lcd.print("Y");
    }
    else if (miTestText->getValue() == ! 123456) {
      lcd.setCursor(13, 1);
      lcd.print("N");
    }

**Comment by FranzBangar** [comment]
You can only directly (==) compare data of the same type (integer to integer, char to char, ...). In your code you are comparing string from text->getValue() to an integer which cannot be compared this way. Because text is a (array of `char` types) and getValue() only returns a pointer to the first character of this text, you need to use a function to compare two strings.

```
if( strcmp(miTestText->getValue(), "123456") == 0) {
    /* do something */
}
else{
    /* do something else */
}
```

Notice three things:
- strcmp function [strcmp()](http://www.cplusplus.com/reference/cstring/strcmp/) which returns 0 if both strings passed as arguments are the same
- double quotes around 123456 which means that is a string too
- if you check for a condition to be true in an `if()` statement, you don't have to check the same condition to be false in `else()` because `else()` is exactly for that - when condition is false.

Correct your code and see if it works.

**Comment by fani625** [comment]
Thanks again for your time.
Now it's working fine and I hope this all information will help for others also.
